search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "change-this-secret-key-in-prod-searxng"
  base_url: false
  limiter: false
  public_instance: false
